Repository plone/plone.app.caching, pull requests merged in 2021-02, with the labels that each got.

#65 Restore and modernize resourceRegistries ETag.
  docs/caching-proxies.rst
  docs/etags.rst
  news/61.feature
  plone/app/caching/lastmodified.py
  plone/app/caching/operations/configure.zcml
  plone/app/caching/operations/etags.py
  plone/app/caching/profiles/with-caching-proxy-splitviews/registry.xml
  plone/app/caching/profiles/with-caching-proxy/registry.xml
  plone/app/caching/profiles/without-caching-proxy/registry.xml
  plone/app/caching/tests/test_integration.py
  plone/app/caching/tests/test_profile_with_caching_proxy.py
  plone/app/caching/tests/test_profile_without_caching_proxy.py
  plone/app/caching/tests/test_purge.py
  plone/app/caching/tests/test_utils.py
Labels: 04 type: enhancement, 13 prio: normal, 22 status: in-progress, 35 needs: rebase

#73 Do not break if some custom code provides an alias for
  news/72.bugfix
  plone/app/caching/caching.zcml
Labels: 24 status: ready

#71 Add more purge paths for images and downloads
  news/71.bugfix
  plone/app/caching/operations/etags.py
  plone/app/caching/purge.py
  plone/app/caching/tests/test_integration.py
  plone/app/caching/tests/test_profile_with_caching_proxy.py
  plone/app/caching/tests/test_profile_without_caching_proxy.py
  plone/app/caching/tests/test_purge.py
  plone/app/caching/tests/test_utils.py
Labels: 01 type: bug, 13 prio: normal, 23 status: testing
